### ISSUE TITLE
Clojure Clients

### ISSUE THREAD

**Issue by xcthulhu** [ptaoussanis/sente#171] opened 2015-10-05 02:59 UTC
It would be extremely helpful for testing if Clojure could act as both a server and a client for sente.

This could be perhaps be done by wrapping `org.eclipse.jetty.websocket/websocket-client` suitably.

**Comment by danielcompton** [comment] 2015-10-05 04:17
This is a dupe of #80. Closing to continue the discussion there.

**Closed by danielcompton** 2015-10-05 04:17 UTC
