### ISSUE TITLE
handling auth reconnect vs server restart

### ISSUE THREAD

**Issue by sritchie** [ptaoussanis/sente#105] opened 2015-02-16 19:02 UTC
Hey Peter,

I'm looking for advice on a way to distinguish between a client-triggered reconnect and a sudden reconnect that the client didn't expect. We hold a :redirect in our client-side Om state, and trigger a reconnect when a user authenticates to update their session server side.

The problem I'm running into is that if the server restarts, these redirects get triggered for all connected users. It'd be great to have a flag or something inside the sente map that this redirect was requested. What do you think? Is there some cleaner way to handle this?

**Comment by ptaoussanis** [comment] 2015-02-17 05:11
Hey Sam, I'm not sure I'm completely following.

Clients attempt to auto reconnect to the server when their connection fails for any reason (e.g. the server dies or reboots, the client<->server net connection is broken for any reason, the client calls `chsk-reconnect!`, etc.).

Just to clarify that I'm understanding: you want clients to be able to distinguish between an auto-reconnect that was initiated by a `chsk-reconnect!` call vs any of the other causes?

Or you want the server to be able to distinguish between an auto-reconnect that was initiated by a `chsk-reconnect!` call vs any of the other causes?

**Comment by sritchie** [comment] 2015-02-17 05:45
correct here:

"You want clients to be able to distinguish between an auto-reconnect that was initiated by a chsk-reconnect! call vs any of the other causes?"

This way I can trigger the auto-redirect if the client initiates a reconnect, otherwise just ignore it. (There's probably a better way to think through my design.)

**Comment by ptaoussanis** [comment] 2015-02-17 05:59
> correct here:
> "You want clients to be able to distinguish between an auto-reconnect that was initiated by a chsk-reconnect! call vs any of the other causes?"

Wouldn't the client already always know when a reconnect is caused by a `chsk-reconnect!` call though? It's the one making the call, no?

> This way I can trigger the auto-redirect if the client initiates a reconnect, otherwise just ignore it. (There's probably a better way to think through my design.)

I think what I'm not following is this: where is your logic located that wants to be able to make the distinction?

So let's say there's a user-facing "Login" button. When the button's clicked, a `chsk-reconnect!` call is made. At that point we know that we've just initiated a manual auto-reconnect.

But now some other code is being triggered (where?) - which needs to know that a _manual_ auto-reconnect is taking place? Is that right?

Sorry, am a bit tired - you may need to explain this like you would to a 5-year old :-)

**Comment by sritchie** [comment] 2015-02-18 18:57
Hey Peter,

Sorry, I was a bit vague on what I'm trying to do. When you say "Wouldn't the client already always know when a reconnect is caused by a chsk-reconnect!", that's correct, except that that method call is async. The client has no way of knowing when the reconnect actually occurs, because I can't use a callback with that reconnect call.

Here are the steps our site takes for a user login:
- The client sends an event of type `:login/form` across the wire, with username and password with a callback that waits for the response.
- On a successful response, the client dispatches a `:reconnect` event into our local pubsub.
- The listener sees that message and calls `(sente/chsk-reconnect! (:chsk chsk))` (That call is async, so I can't know when it completes.)
- On the client side pattern matcher for server/client events, now, every time I see a new reconnect that's not the first-open, I send an `::auth` request to the server. (This is because I want to make sure that the client-side copy of the user's session information is fresh.)

```clojure
[:chsk/state {:open? true}] (do (sente/debugf ":chsk/state :open? true; sending ::auth event to server.")
                                     (send-fn [::auth {}]))
```

- The server responds with this:

```clojure
[::route/auth {:session (route/user-session ring-req)}]
```

- The client handles that event by updating the session and possiby performing a redirect:

```clojure
(defmethod route/handle-event ::route/auth
  [_ {:keys [session cursor component]}]
  (let [current-session (state/session component)
        redirect (or (:redirect current-session)
                     (if (:secure? session)
                       {:name ::route/profile-races :opts {:date "upcoming"}}
                       {:name ::route/login :opts {}}))]
    (dispatch! component :update-session session)
    (->> (assoc current-session :redirect redirect)
         (redirect! component))))
```

Phew. my problem is that that final auth handshake and the redirect is happening whenever I restart the server. What I'd love to be able to do is do that auth thing inside a callback supplied to "reconnect!". I'm clearly hooking into the wrong spot to initiate the handshake.

Does that make sense? Any thoughts on how to do this better?

Thanks for bearing with me on the description :)

**Comment by ptaoussanis** [comment] 2015-02-21 05:09
Okay, gotcha - thanks for the detailed clarification. This is something likely best handled by a small mod to Sente. Just juggling a few priority tasks atm, but will try get back to you later today with a fix.

**Comment by ptaoussanis** [comment] 2015-02-21 09:05
Hey Sam, just pushed `[com.taoensso/sente "1.4.0-SNAPSHOT"]` to Clojars.

Haven't had much time to test it, but the idea is that your client-side state-change event msgs will now contain a `:requested-reconnect?` flag that you can check for in your pattern matching.

Let me know how this works out for you?

Cheers! :-)

**Comment by sritchie** [comment] 2015-02-22 18:04
@ptaoussanis awesome! I'm off for the next day or two, but I'll get at this right away when I get back. That fix sounds perfect for us.

**Comment by ptaoussanis** [comment] 2015-02-23 04:01
@sritchie np - enjoy your down-time! Cheers :-)

**Comment by sritchie** [comment] 2015-02-25 02:37
Okay, trying to do this upgrade (from a fixed 1.3.0-SNAPSHOT) now. I'm running into a couple of issues that you may have seen. The first is

```clojure
No reader function for tag +clj, compiling:(taoensso/sente:606:89)
```

when I try to compile at the REPL. This is new, and I'm not sure what's up. We might be able to fix that one with `:jar-exclusions`, as reffed in the cljx sample: https://github.com/lynaghk/cljx/blob/master/sample.project.clj#L22

The next is that none of my server pushes seem to be making it across the wire when I use `:client-id`. I'm using the Chrome dev tools to inspect the websocket contents - Pushing to `:client-uuid` in that old `1.3.0-SNAPSHOT` worked great. Did something change since you pushed that initial version?

The initial handshake is the only thing that gets through, and looks like this:

```clojure
[:chsk/handshake [:taoensso.sente/nil-uid "QMGw5Hd+2EH34KJTu7u55lO96WO1D8KP4ptafZZ8WQGw9K8Bq3EoBhbG2GS2OxvSyE5K66lWmxbsSPRO"]]
```

Not sure if the `nil-uid` is significant.

**Comment by sritchie** [comment] 2015-02-25 02:49
Really strange on the `:client-id`. I can get you some more information on this too, or follow some debug steps if you have any advice. i'm on Chrome 40.0.2214.111 (64-bit).

**Comment by ptaoussanis** [comment] 2015-02-28 12:00
Hey Sam, sorry for the delay replying - have been travelling.

> No reader function for tag +clj, compiling:(taoensso/sente:606:89)

This is almost certainly a problem with your Cljx workflow somewhere. The `+clj`, `+cljs` tags are supposed to be stripped when producing `.clj`/`.cljs` files. So it looks like some part of your process is actually trying to consume the unprocessed `.cljx` file while those tags are still present.

Have you changed any of your tooling or anything in your workflow recently? If it's happening only at your REPL, I'd start by checking your Cljx REPL middleware.

> The next is that none of my server pushes seem to be making it across the wire when I use :client-id

I'd start by resolving the reader tag problem; it's possible something is faulty with your build. If you get the tag problem resolved and `lein clean; lein cljx once` doesn't help, then I'd try the reference example to see if the `:client-id` is working there as expected or no. Let me know how that goes and we'll proceed from there?

> `[:chsk/handshake [:taoensso.sente/nil-uid "QMGw5Hd+2EH34KJTu7u55lO96WO1D8KP4ptafZZ8WQGw9K8Bq3EoBhbG2GS2OxvSyE5K66lWmxbsSPRO"]]`
> Not sure if the nil-uid is significant.

Well this implies that the server's `(user-id-fn <ring-req-with-client-id-key>)` call is resulting in `nil`. The default `user-id-fn` is `(fn [ring-req] (get-in ring-req [:session :uid])`.

Are you expecting there to be a `:uid` in the session during handshake?

**Comment by ptaoussanis** [comment] 2015-02-28 12:59
Re-reading now, it does seem likely that your server->user push trouble at least involves your `user-id-fn`. You'll probably want a server-side `make-channel-socket!` call that overrides the default `:user-id-fn` to something like:

`(fn [ring-req] (or (get-in ring-req [:session :uid]) (get ring-req :client-id)))`. 

But if you've never overridden the `:user-id-fn` then we still need an explanation for why server->client `:client-id` pushes work for you with v1.3.0 but not >v1.3.0.

So to summarise ideas:
1. Could the build artefacts be broken or outdated?
2. Were you overriding `:user-id-fn` before? What about now?
3. Have you searched your code base for possible obsolete `:client-uuid` references?
4. Do you see server->client pushes failing for both WebSockets and Ajax?

```
[:chsk/handshake [:taoensso.sente/nil-uid "QMGw5Hd+2EH34KJTu7u55lO96WO1D8KP4ptafZZ8WQGw9K8Bq3EoBhbG2GS2OxvSyE5K66lWmxbsSPRO"]]
```

This implies that the user has **not** been given a user-id. Server->user push will not be possible for this user unless it's a broadcast push to `:sente/all-users-without-uid`.

If your `:user-id-fn` is correct, you *should* be seeing an appropriate user-id assigned during handshake.

**Comment by sritchie** [comment] 2015-03-01 23:41
Ugh, this was my fault. I'd added some indirection, and as you suggested I still has my `:user-id-fn` as `:client-uuid`. I was destructuring that field properly for responses, but not setting it up right.

I'm going to see if I can get these cljx issues gone, then I'll close up these issues.

Thanks!

**Comment by ptaoussanis** [comment] 2015-03-02 11:57
No problem Sam, thanks for keeping me updated. Cheers! :-)

**Comment by ptaoussanis** [comment] 2015-03-02 20:44
Closing this issue for now since we've got the separate .cljx issue open.

**Closed by ptaoussanis** 2015-03-02 20:44 UTC
Labels: ideas welcome
