### ISSUE TITLE
Chsk router `event-msg-handler` error: [:chsk/recv [:chsk/ws-ping]] Error: No matching clause: :chsk/ws-ping

### ISSUE THREAD

**Issue by gered** [ptaoussanis/sente#277] opened 2016-10-25 21:16 UTC
Hey,

We recently updated to Sente 1.11.0 and have noticed that we're seldomly getting this error popping up:

```
ERROR [taoensso.sente:1549] - Chsk router `event-msg-handler` error: [:chsk/recv [:chsk/ws-ping]]
Error: No matching clause: :chsk/ws-ping
taoensso.timbre.appenders.core.console_appender.cljs$core$IFn$_invoke$arity$variadic    @   core.cljs?rel=1477421621061:181
(anonymous function)    @   timbre.cljs?rel=1477421621274:458
(anonymous function)    @   core.cljs:6307
cljs.core.PersistentArrayMap.cljs$core$IKVReduce$_kv_reduce$arity$3 @   core.cljs:6307
cljs$core$_kv_reduce    @   core.cljs:602
cljs$core$reduce_kv @   core.cljs:2405
taoensso$timbre$_log_BANG_  @   timbre.cljs?rel=1477421621274:415
(anonymous function)    @   sente.cljc?rel=1477421629761:1549
(anonymous function)    @   sente.cljc?rel=1477421629761:1523
(anonymous function)    @   sente.cljc?rel=1477421629761:1536
(anonymous function)    @   sente.cljc?rel=1477421629761:1529
taoensso$sente$_start_chsk_router_BANG__$_state_machine__64046__auto____1   @   sente.cljc?rel=1477421629761:1529
taoensso$sente$_start_chsk_router_BANG__$_state_machine__64046__auto__  @   sente.cljc?rel=1477421629761:1529
cljs$core$async$impl$ioc_helpers$run_state_machine  @   ioc_helpers.cljs?rel=1477421625795:35
cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped  @   ioc_helpers.cljs?rel=1477421625795:39
(anonymous function)    @   async.cljs?rel=1477421627872:480
(anonymous function)    @   async.cljs?rel=1477421627872:188
(anonymous function)    @   channels.cljs?rel=1477421624858:61
cljs$core$async$impl$dispatch$process_messages  @   dispatch.cljs?rel=1477421624723:19
channel.port1.onmessage @   nexttick.js:211
```

Apologies for the ugly stack trace (copied from Chrome console log).

We don't think this is anything wrong with our application code (since we did not get this error ever before upgrading). Wondering if it has something to do with the `:chsk/recv` event as it seems there's now (sometimes?) a `:chsk/ws-ping` inside it? I thought previously these were always top-level events.

Any thoughts?

Thanks!

**Comment by danielcompton** [comment] 2016-10-25 21:53
Looks like a dupe of #274?

**Comment by yogthos** [comment] 2016-10-25 22:04
The target has been cleaned since the library was updated, so I don't think this is due to stale artifacts.

**Comment by gered** [comment] 2016-10-25 23:29
Indeed, I run `lein clean` _all_ the time before either `lein figwheel` or `lein run` as I've just seen too many issues with seemingly random stale artifacts getting left in causing problems.

**Comment by ptaoussanis** [comment] 2016-10-26 03:27
Hey there :-)

Thanks Daniel, Dmitri!

What version of Sente are you migrating _from_? Possibly v1.8.x?

Looks like this could be _related_ to #274. I'll note that the cause there turned out not to be stale artifacts, but a version incompatibility between a new server and some old clients that were still hanging around.

In this case, very old clients (v1.8.x if I recall correctly) sent ping messages in a different format. If received by a new (e.g. v1.11.x) server, they'll be interpreted as an `[:chsk/recv [:chsk/ws-ping]]` event.

That's not harmful, the event can just be ignored. But it looks like you might have a `case` somewhere in your event-message handler flow that's tripping up on the unexpected event coming from those few old clients that might still be out in the wild. (This'd explain why the problem is rare).

You'll just need to find the offending `case` statement and either put in a provision for this event (to noop), or just put in a default noop behaviour.

Does that help / make sense?


Will also see about possibly cutting a point release that automatically filters these old-style pings to avoid confusion or potential problems.

**Comment by gered** [comment] 2016-10-26 12:26
Hey!

We upgraded from 1.9.0. I seem to recall there was some event handler changes we had to do at the time (or rather, that Dmitri did) so I guess it's possible something small was missed a that time. At any rate, it's been over a week since the upgrade and we've not pushed this change out to our users yet I don't think. Regardless, this is an error we've only seen locally on development builds (so far) so there couldn't be any old clients sending out old-style pings.

If we had just upgraded to 1.11.0, I could probably believe that my browser was caching an old copy of the compiled CLJS with 1.9.0 code in it, but given the time since the upgrade and how much development work I've done since this in our app (and all the rebuilds along with it), I have a feeling this probably isn't the case here.

In the mean time I'll see about doing another once-over of all our event handling code and seeing if anything sticks out to me.

**Comment by ptaoussanis** [comment] 2016-10-26 14:39
Gotcha, thanks for the extra info.

In case it's helpful for debugging, I'll just note:

- A "No matching clause" error implies either a `case` or `condp` with missing clause somewhere.
- The "Chsk router `event-msg-handler` error" means that the `case` or `condp` is being hit somewhere within a chsk router handler.
- The input event that's causing problems is `[:chsk/recv [:chsk/ws-ping]]`.

So you may be able to debug by manually passing `[:chsk/recv [:chsk/ws-ping]]` along to your top-level event handler fn and digging to see if it may be tripping up a `case` or `condp` somewhere.

Hope that helps! :-)

**Comment by gered** [comment] 2016-10-26 22:55
For sure, thanks a bunch! I should be able to devote some time to investigate this more thoroughly over the next couple days (since it doesn't actually break anything it's been hard to prioritize it once we discovered the problem, heh).

**Comment by gered** [comment] 2016-11-01 14:48
Still unfortunately haven't been able to dedicate a lot of time to hunting this down as of yet, but just wanted to quickly share what just happened to me.

Running a local dev instance of the app, no other clients connecting to it, only my single instance (single tab) of Chrome.

![image](https://cloud.githubusercontent.com/assets/633985/19893525/d5cab71e-a01f-11e6-8931-15324106f2af.png)

The standalone `:chsk/ws-ping` seemed to just be a one off there (and it did result in the same error I shared previously in the browser console). Note that there was no code changes reloading in figwheel or anything like that. The "reload-nodr-data" message is something triggered by a button on the project I'm working on that simply requests updated data from the server to be displayed on the page. There's nothing fancy going on there as far as Sente client/server communication is concerned.

Once I noticed this, I tried clicking the same button again:

![image](https://cloud.githubusercontent.com/assets/633985/19893723/82888576-a020-11e6-9e7c-466fe9b21a4b.png)

And no problems. Really weird.

Anyway, again, just haven't been able to dedicate the time to do a proper code-review yet (my to-do list seems to only grow, heh.... _sigh_). Hopefully soon.

**Comment by kenrestivo** [comment] 2017-01-30 05:34
I had this problem

The solution was this in dependencies:
```clojure
                 [com.taoensso/sente "1.11.0" :exclusions [com.taoensso/encore]]
                 [com.taoensso/timbre "4.8.0" :exclusions [com.taoensso/encore]]
                 [com.taoensso/encore "2.87.0"] ;; because taonesso release versions don't seem to be regression tested against each other?

```

**Comment by zh217** [comment] 2017-01-30 16:54
I encountered this problem too.

In my case 
```
[com.fzakaria/slf4j-timbre "0.3.4"]
[org.apache.logging.log4j/log4j-to-slf4j "2.8"]
```
would cause the problem, whereas
```
[com.fzakaria/slf4j-timbre "0.3.2"]
[org.apache.logging.log4j/log4j-to-slf4j "2.7"]
```
would be OK.

I have no idea what is happening here.

**Comment by gered** [comment] 2017-01-30 20:29
Hmm, interesting. I'll have to give this a try. Have still been seeing the error come up periodically since my last post in this issue. After going through the code several times I did not find anything that I could see that would cause this (of course it's possible I missed something). Hopefully these dependency exclusions get rid of it in my project too, even if it is a bit of a wonky "fix" for now.

**Comment by kenrestivo** [comment] 2017-02-01 03:33
I've long seen problems with slf4j and log4j colliding with timbre in strange ways.

But what's troubling is to see those problems in otherwise unrelated libraries bubble up into other taonesso projects like sente.

Also, I don't know what kind of regression testing is done, but it's also troubling that the latest version of X, Y, and Z from the same developer don't work together.

**Comment by ptaoussanis** [comment] 2017-03-24 18:53
Hi folks,

So as I mentioned before, it's not clear to me how the initially described problem could be the result of a dependency issue.

Think it's possible there's confusion happening here between the message (no matching `:chsk/ws-ping` clause, which indicates a client/server incompatibility), and the messenger (Timbre).

A client/server incompatibility or buggy handler is the best guess I can make with the concrete info provided here, otherwise would recommend checking my [earlier debugging suggestions](https://github.com/ptaoussanis/sente/issues/277#issuecomment-256367830).

> What has sente to do with a backend logging library ...

The error you're seeing is being reported by Timbre, which provides cross-platform logging.

> Also, I don't know what kind of regression testing is done, but it's also troubling that the latest version of X, Y, and Z from the same developer don't work together.

Hi Ken-

The "same developer" in this case is just myself, and I'm juggling quite a few balls trying to find free time after work and at the weekends to continue supporting and putting out open source software like Sente.

It's not clear to me that the trouble anyone is seeing here is actually the result of a dependency conflict, but I will note that dependency conflicts are indeed fairly common and unfortunate.

In any event, the general strategy you need to be aware of is pretty [straightforward](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) - and using the latest library versions should generally work except in the rare cases of an unexpected bug.

**Comment by ptaoussanis** [comment] 2017-03-24 18:56
So to clarify: is anyone still experiencing this problem (no matching clause: :chsk/ws-ping)?

If anyone is, could you possibly attempt the [debug suggestion](https://github.com/ptaoussanis/sente/issues/277#issuecomment-256367830) made earlier?

Otherwise, can this issue be closed?

Thanks!

**Comment by kenrestivo** [comment] 2017-03-25 03:47
I do appreciate what you're doing here, and I understand you're busy. Sorry for being cranky.

I haven't used Sente in a while but Timbre has been solid in recent versions.

**Comment by ptaoussanis** [comment] 2017-03-25 08:25
@kenrestivo No problem :-)

**Comment by zh217** [comment] 2017-03-25 09:14
@ptaoussanis First of all I would like to say thank you for taking your time maintaining these wonderful libraries.

As for the issue itself, I haven't had any problems with recent versions of the related libraries.

I looked at several of the problematic builds of my private project, copied their relevant dependency versions to the sente example project, and yes I do encounter problems using these exact versions. You can see them [here](https://github.com/zh217/sente/commit/c5c5ce0e117fa59744ab554fe04ed870fb622946) .

**Comment by ptaoussanis** [comment] 2017-03-25 09:24
@zh217 You're very welcome, thanks for saying so.

> As for the issue itself, I haven't had any problems with recent versions of the related libraries.

Great, thanks for the confirmation!

> I looked at several of the problematic builds of my private project, copied their relevant dependency versions to the sente example project, and yes I do encounter problems using these exact versions. You can see them here .

So in case you wanted to debug this further out of curiosity, etc. - first step would be running `lein deps :tree`. There's two main possible causes of the problem you were seeing:

1. A dependency conflict (common case, which you could identify with `lein deps :tree`).
2. An actual version incompatibility of some kind due to a bug (these are rare, but can happen).

I will note that I see you're using `slf4j-timbre` which afaik is (was?) unusually sensitive to things like dependency versions because of the way it needs to be compiled for compatibility with SLF4J. Not too familiar with the specifics, but may also suggest just searching the slf4j-timbre GitHub issues in case something relevant pops up.

Cheers!

**Closed** 2017-04-17 10:09 UTC
Labels: can close?
