### ISSUE TITLE
Eliminate js/window for nodejs compatibility

### ISSUE THREAD

**Issue by TerjeNorderhaug** [ptaoussanis/sente#209] opened 2016-03-05 05:54 UTC
As `js/window` is specific for browsers, for better compatibility with clojurescript on nodejs, consider using `goog.global` rather than `js/window` as in `goog.global/WebSocket` instead of `(aget js/window "WebSocket") `- or alternatively just `js/WebSocket`.

**Comment by ptaoussanis** [comment] 2016-03-05 06:37
Hi Terje, thanks for this.

Would ideally like to wait on a response from @theasp first at https://github.com/ptaoussanis/encore/issues/21 since he wrote the Node stuff and it's currently my understanding that he might already used Sente in this way without the need for any changes (?).

As I mentioned, I don't use Node myself so can't provide any guidance here. If any changes do turn out to be necessary, they'll likely need to come in the form of a PR.

In principle would be happy to make this as smooth as possible for Node users, would just like some confirmation before we adopt a particular plan.

Cheers :-)

**Comment by ptaoussanis** [comment] 2016-03-05 06:37
Also pinging @whamtet - any advice on this? Thanks!

**Comment by ptaoussanis** [comment] 2016-03-06 13:24
Um, okay- something odd definitely going on. All trace of both issues seems
to be gone and Terje's GitHub page is 404'ing.

Perhaps he deleted his account and GitHub auto-kills all issues a deleted
user created?

Let's give it some time, maybe they're just having a temporary problem.

Will open a fresh issue so long.


On Sat, Mar 5, 2016 at 12:54 PM, Terje Norderhaug <notifications@github.com>
wrote:

> As js/window is specific for browsers, for better compatibility with
> clojurescript on nodejs, consider using goog.global rather than js/window
> as in goog.global/WebSocket instead of (aget js/window "WebSocket") - or
> alternatively just js/WebSocket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptaoussanis/sente/issues/209>.
>



-- 
*Peter Taoussanis*
ptaoussanis@taoensso.com
taoensso.com <https://www.taoensso.com>

**Comment by whamtet** [comment] 2016-03-06 15:31
Mysterious,

ok.  Could try again in the morning.  From what I can tell the js/window
references are only in sente.cljx and lie on the client side.  Do we need
to get rid of them?

Matt

**Comment by whamtet** [comment] 2016-03-06 16:00
Ok, sure.  Would you like me to put in a pr for it?

**Comment by ptaoussanis** [comment] 2016-03-07 03:38
@TerjeNorderhaug Hi Terje, could you please clarify: you're trying to use Sente from Node as a **server** (not client), and you're running into errors with `js/window`, etc.? Could you possibly include a reproducible example?

Please note that Sente currently supports Node on the server end but **not** the client end.

Does that make sense?

**Comment by TerjeNorderhaug** [comment] 2016-03-07 05:40
The _Terje's GitHub page is 404'ing_ related issues was caused by a github bot flagging me as a bot, for no obvious reason.

**Comment by whamtet** [comment] 2016-03-07 05:42
Quick!  The bots are revolting!  What was the problem you had with js/
window on node?

**Comment by xcthulhu** [comment] 2016-03-27 16:58
This isn't just a node.js thing ; it effects slimerjs and phantomjs and interferes with using those systems for unit testing.

Likewise, it would be convenient if node.js could be a client, too....

**Comment by ptaoussanis** [comment] 2016-03-28 02:24
Just to clarify: Sente was initially a :clj server + :cljs client since that's what I needed myself, and it was a place to start.

The node.js client work prompted a small refactor which added support for :cljs servers too.

**So as of today we have support for #{:clj :cljs :node} servers and #{:cljs} clients.**

Some further refactoring will be necessary to add support for :clj clients and/or :node clients. Does that make sense?

I don't have a particular need for either of these myself and have some other priorities, so won't be able to handle these myself - but PRs would be welcome :-)

Does that make sense?

**Comment by xcthulhu** [comment] 2016-03-28 14:00
> Some further refactoring will be necessary to add support for :clj clients and/or :node clients. Does that make sense?

Sure; but I was just saying that there's other headless javascript environments besides node that don't have js/window besides node.

Personally, I don't have any pressing need for a :clj client (or a headless :cljs client beyond merely unit testing).

IMO, a refactor for headless :cljs would be easier than a :clj refactor ; I have admittedly been scared to refactor this code in the past, since without unit tests I wasn't sure if I was breaking things.

**Comment by DaveWM** [comment] 2016-07-10 20:05
Hey guys, I've submitted a PR to allow nodejs clients. It might also enable nodejs servers, but I haven't tested that.

**Comment by ptaoussanis** [comment] 2016-07-14 06:53
Resolved with #243

**Closed by ptaoussanis** 2016-07-14 06:53 UTC
Labels: ideas welcome, pull requests welcome
