### ISSUE TITLE
Issue with send-message-event using example app

### ISSUE THREAD

**Issue by brandonparsons** [ptaoussanis/sente#115] opened 2015-03-15 20:29 UTC
I keep getting errors on exactly the second event (and only the second event) sent when clicking the `Send Message Event` button from the example app.

`[Error] Error: nth not supported on this type cljs.core/Keyword
	cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (ioc_helpers.js, line 89)
	(anonymous function) (ioc_helpers.js, line 103)
	(anonymous function) (async.js, line 6517)
	(anonymous function) (channels.js, line 369)
	cljs$core$async$impl$dispatch$process_messages (dispatch.js, line 20)
	onmessage (nexttick.js, line 148)`

Error throws from this line:

```clojure
(defn run-state-machine-wrapped [state]
  (try
    (run-state-machine state)
    (catch js/Object ex
      (impl/close! ^not-native (aget-object state USER-START-IDX))
      (throw ex))))
```

**Comment by brandonparsons** [comment] 2015-03-15 21:01
I'm not sure if this is an issue with Sente, or with the Rente example app (see https://github.com/enterlab/rente/issues/2)

**Comment by luposlip** [comment] 2015-03-17 06:59
:+1:
Putting my name here to receive updates.

**Comment by ptaoussanis** [comment] 2015-03-20 07:21
Hi Brandon, Henrik.

Sorry for the delay replying, have been travelling. I've never used or looked closely at Rente, so can't comment there yet.

Would you mind trying the Sente [reference example](https://github.com/ptaoussanis/sente/tree/master/example-project) and seeing if you can reproduce the error there?

Let me know how that goes and I can investigate from there.

Cheers :-)

**Comment by ptaoussanis** [comment] 2015-03-20 07:30
Should just mention: this smells like a dependency issue. I've been avoiding recent ClojureScript releases lately since they keep breaking things for me (tooling, etc.). There've been some odd dependency conflicts between things like tools.reader, core.async and ClojureScript where one needs specific compatible versions otherwise one can run into weird random errors similar to this.

Not saying that's the cause, just mentioning it in case that rings a bell to anyone that's already spent time looking into this.

**Comment by tuhlmann** [comment] 2015-03-20 12:54
I have a version of my (toy) application that includes the Sente example application, and I have one that uses components (Stuart Sierra), basically ripped off of rente (https://github.com/enterlab/rente).
In both version I use the same libraries (see below).

The sente example code works fine with these libraries while the componentized code throws that exception on the second (and sometimes it's not the second but the first) pushed message.

Could the problem be the order in which (sente, handler, http-kit) the components are assembled? But then, the error occurs again if I reload the browser page.

An interesting thing I just tested: If I connect two browsers with the same user-id the message is pushed to both browsers (as it should be). But only in the browser that I reloaded this error occurs- and it occurs on the first click, not the second. 

Do you have any idea how I could track this down further?

```
  :dependencies [[org.clojure/clojure "1.7.0-alpha5"]
                 [cljsjs/react "0.13.0-0"]
                 [reagent "0.5.0"]
                 [reagent-forms "0.4.5"]
                 [reagent-utils "0.1.4"]
                 [secretary "1.2.3-SNAPSHOT"]
                 [org.clojure/clojurescript "0.0-3126"]
                 [ring/ring-defaults "0.1.4"]
                 [com.stuartsierra/component "0.2.3"]
                 [org.clojure/tools.namespace "0.2.7"]
                 [prone "0.8.1"]
                 [compojure "1.3.2"]
                 [environ "1.0.0"]
                 [hiccup "1.0.5"]
                 [org.clojure/core.cache "0.6.4"]
                 [org.clojure/core.match "0.2.2"]
                 [org.clojure/tools.logging "0.3.1"] ;; differs
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [com.cemerick/pomegranate "0.3.0"]
                 [buddy/buddy-core "0.4.1"]
                 [buddy/buddy-sign "0.4.0"]
                 [buddy/buddy-hashers "0.4.0"]
                 [buddy/buddy-auth "0.4.0"]
                 [lib-noir "0.9.5"]
                 [com.novemberain/validateur "2.4.2"]
                 [com.taoensso/sente "1.4.1"]
                 [com.taoensso/timbre "3.4.0"]
                 [com.cognitect/transit-clj  "0.8.269"]
                 [com.cognitect/transit-cljs "0.8.205"]
                 [com.novemberain/monger "2.1.0"]
                 [asset-minifier "0.1.6"]
                 [http-kit "2.1.19"]
                 [riddley "0.1.9"]
                 [prismatic/schema "0.4.0"]
                 [clj-time "0.9.0"]
                 [org.clojure/data.json "0.2.6"]
                 [clojure-watch "LATEST"]]
```

**Comment by ptaoussanis** [comment] 2015-03-20 15:12
Hi Torsten, could you show me how you're doing the componentization?

The error you're seeing seems to be coming from core.async, so I'd suggest taking a particular look at any of your code that starts or stops Sente's routers (these are core.async loops).

**Comment by tuhlmann** [comment] 2015-03-20 15:44
I found the problem!

At https://github.com/enterlab/rente/blob/master/src/rente/client/app.cljs#L31 (I used that same code), an additional go-loop is instantiated. I don't really know why, I think that make no sense since all the client side event handling is done in https://github.com/enterlab/rente/blob/master/src/rente/client/ws.cljs which also starts a router in the end and is the place where all the events end up.

I removed this second go-loop and the code worked. I looked at all the code in all the places, but this piece, I just took for granted... Oh well, learned a ton.

Thanks,
Torsten.

**Comment by ptaoussanis** [comment] 2015-03-20 17:30
Oh, fantastic! Thanks for following up.

Yeah haven't looked at the Rente code or what it's doing exactly, but some kind of extraneous/faulty go loop could explain the error you're seeing.

Let's keep this open until Rente's author confirms that you've identified the correct cause (@luposlip?).

Otherwise @tuhlmann, @luposlip: feel free to ping if either of you could use any extra info for debugging, etc.

Cheers :-)

**Comment by luposlip** [comment] 2015-03-24 17:04
Hi both,

Thanks for your input @ptaoussanis and @tuhlmann.
When I remove the go-loop in app.cljs, the app isn't working.

I'll go into more details in the ref'ed issue on enterlab/rente.

Best,
Henrik

**Comment by brandonparsons** [comment] 2015-03-26 01:23
Thanks for looking into this! I keep missing github notifications as I"m trying to cut down on my emails :)

**Comment by ptaoussanis** [comment] 2015-03-26 06:08
Closing now, thanks again for everyone's assistance. Cheers :-)

**Closed by ptaoussanis** 2015-03-26 06:08 UTC
Labels: blocked/waiting
