### ISSUE TITLE
Sente not detecting non-terminating client disconnects? (e.g. sudden power loss / airplane mode)

### ISSUE THREAD

**Issue by altV** [ptaoussanis/sente#230] opened 2016-05-02 14:56 UTC
I'm using android default browser, and I see its id in `connected-ids` atom after turning on Flight mode or phone restarts.

Closing android browser or navigating away from the page works fine, though.

**Comment by ptaoussanis** [comment] 2016-05-02 15:03
Hi there, thanks for the report. What Android device, browser, and HTTP
server are you using?

Is this over Ajax, websockets, or both?

**Comment by altV** [comment] 2016-05-07 23:05
Hihi,
sorry for delayed reply!

Samsung Galaxy S6 / Default browser 

`"Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36"`

It is over websocket.
How would I approach debugging?

**Comment by danielcompton** [comment] 2016-05-07 23:23
Is this using the sample application? Turning the logging level up and providing the server and client logs would probably be quite a good start for tracking this down.

**Comment by altV** [comment] 2016-05-08 00:06
sorry, new to clojure -- how do I switch on logs on sente?

**Comment by danielcompton** [comment] 2016-05-08 07:07
https://github.com/ptaoussanis/sente/blob/master/example-project/src/example/client.cljs#L18 and https://github.com/ptaoussanis/sente/blob/master/example-project/src/example/server.clj#L29. I recommend running from the example project so we can help debug from a known base.

**Comment by ptaoussanis** [comment] 2016-05-09 05:26
Just to add to Daniel's good advice - the most likely causes of Sente not reflecting a disconnected client would be (in order):

1. It's an Ajax client, and you're expecting the disconnect to reflect immediately. In fact, Ajax clients are designed to only show up as disconnected ~5 seconds after last activity.

2. The underlying HTTP server is buggy and not reliably calling `on-close` when it needs to.

3. A bug in Sente.


Debugging this with the example project, I'd start by making sure you've ruled out (1) for sure, then I'd suggest ruling out (2) by trying an alternative http server.

Hope that helps, cheers! :-)

**Comment by altV** [comment] 2016-05-09 17:31
- It is not an Ajax client, to my understanding.
- I could not get example application to work using `cd example-app && lein run`, it opens a web page with four options and buttons doesn't seem to do anything
- I've looked through the Sente source code, and I understand that it should be a bug in http-kit that figwheel is using
- I have upgraded http-kit to the latest 2.1.19 version and it didn't help. Will try to switch to different http servers

Next steps:
- get example-app to work
- debug with netstat?
- ask http-kit team on how to debug and how to build minimal example?

**Comment by danielcompton** [comment] 2016-05-09 22:25
Hmm, looks like there's a problem with the example project, it didn't work for me either.

**Comment by ptaoussanis** [comment] 2016-05-10 03:29
@altV Thanks for the info, will follow up in a moment.

@danielcompton Hi Daniel, this is the example project currently on master? Seems to be working for me. Please note that it's started with `cd example-project && lein start` not  `cd example-app && lein run`. What behaviour are you seeing exactly?

I do `lein start`, that causes the Cljs to compile - then the server starts up, producing a bunch of log output to the console. Then a browser window auto-opens. All the buttons + async events are working as expected.

**Comment by ptaoussanis** [comment] 2016-05-10 03:37
@altV Follow up inline

> I could not get example application to work using cd example-app && lein run, it opens a web page with four options and buttons don't seem to do anything

Please note that the example project is started with `cd example-project && lein start`. Does that help resolve the issue with the example project not working?

> I've looked through the Sente source code, and now I understand it should be a bug in http-kit that figwheel is using

Could you please rephrase this, I don't follow? Figwheel isn't included in the reference example; are you including it (or any other plugins) manually?

Please let me know of any changes you might be making to the reference example project.

> I have upgraded http-kit to the latest 2.1.19 version and it didn't help. Will try to switch to different http servers

This is in the example project? Are you sure you're using the latest example project (on master). The current example project already includes the latest+recommended version of http-kit ("2.2.0-alpha1").

> Next steps:

My recommendation:

1. Get reference example to work.
2. Rule out that you're observing normal behaviour for Ajax connections. Log output from the ref example will help determine if your connection is falling back to Ajax for any reason.
3. If you can reproduce the error with the ref example + http-kit, try the ref example + immutant to help establish if the issue is with http-kit specifically.

Then let's go from there.

Thanks!

**Comment by altV** [comment] 2016-05-10 15:52
Thank you, I'll try to do that.

I've just switched to immutant/web (undertow?), and you won't believe this! It is still the same behavior - flight mode on the phone, and the client is still in the `connected-uids`.
My `:user-id-fn (fn [ring-req]
                       "generates unique ID for request"
                       (let [uid (get-in ring-req [:session :saml])
                             user-agent (some-> ring-req :headers (get "user-agent") uap/useragent)]
                         [uid (:client-id ring-req) (:remote-addr ring-req) user-agent]))})]`, not sure if this affects anything.

**Comment by altV** [comment] 2016-05-10 17:17
Peter,

I ran example-project with lein start.
No serious warnings are there in the log. Web server is running on 50210. Web page was auto-opened after run. Buttons do not do anything. Server prints some data in debug log - the only lines are

> 16-05-10 17:11:13 ubuntu-leo INFO [example.server:34] - Starting http-kit...
> 16-05-10 17:11:13 ubuntu-leo INFO [example.server:203] - Web server is running at `http://localhost:50210/`
> Created new window in existing browser session.
> 16-05-10 17:11:24 ubuntu-leo DEBUG [example.server:168] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
> 16-05-10 17:11:34 ubuntu-leo DEBUG [example.server:168] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
> 16-05-10 17:11:44 ubuntu-leo DEBUG [example.server:168] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
> 16-05-10 17:11:54 ubuntu-leo DEBUG [example.server:168] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}
> 16-05-10 17:12:04 ubuntu-leo DEBUG [example.server:168] - Broadcasting server>user: {:ws #{}, :ajax #{}, :any #{}}

Web browser cannot request *main.js* - it's not served (404).
The log shows that it compiled successfully:
Compiling ClojureScript...
Retrieving cljsbuild/cljsbuild/1.1.3/cljsbuild-1.1.3.pom from clojars
Retrieving com/taoensso/sente/1.8.2-alpha1/sente-1.8.2-alpha1.pom from clojars
Retrieving com/taoensso/encore/2.49.0/encore-2.49.0.pom from clojars
Retrieving com/taoensso/truss/1.2.0/truss-1.2.0.pom from clojars
Retrieving com/cognitect/transit-cljs/0.8.237/transit-cljs-0.8.237.jar from central
Retrieving com/cognitect/transit-js/0.8.846/transit-js-0.8.846.jar from central
Retrieving com/taoensso/sente/1.8.2-alpha1/sente-1.8.2-alpha1.jar from clojars
Retrieving com/taoensso/encore/2.49.0/encore-2.49.0.jar from clojars
Retrieving cljsbuild/cljsbuild/1.1.3/cljsbuild-1.1.3.jar from clojars
Retrieving io/aviso/pretty/0.1.23/pretty-0.1.23.jar from clojars
Retrieving com/taoensso/truss/1.2.0/truss-1.2.0.jar from clojars
Compiling "target/main.js" from ["src"]...
Successfully compiled "target/main.js" in 15.449 seconds.

**Comment by altV** [comment] 2016-05-10 18:14
I've copied main.js from target/ to resources/public/
It works now.

Now figuring out how to debug disconnects. Enabling more logging as described above - without it information is not enough from the log.

**Comment by ptaoussanis** [comment] 2016-05-11 02:27
> I've copied main.js from target/ to resources/public/

Thanks for catching this! The project was supposed to contain a symlink; hand't noticed that it was being excluded by `.gitignore`. Fixed in master.

**Comment by ptaoussanis** [comment] 2016-05-11 02:34
> I've just switched to immutant/web (undertow?), and you won't believe this! It is still the same behavior - flight mode on the phone, and the client is still in the connected-uids under :ws key. Back-forward buttons work pretty solid - client dissapears in 5 seconds.

Sorry, can you clarify what you mean by "client dissapears in 5 seconds"?

You connect your phone to a Sente channel socket. The uid is automatically added under the :ws key. You turn on your phone's flight mode to simulate a dropped connection. Then the uid is removed from the :ws key after 5 seconds?

If I've understood that correctly, then that's exactly the correct+expected behaviour. Am I misunderstanding something?

Are you suggesting that everything works correctly with Immutant, but you see different (broken) behaviour with http-kit? Please try be explicit about what behaviour you're expecting to see vs what behaviour you're actually seeing that seems broken.

And if you are seeing behaviour that seems to be broken somehow, I'd ask that we please confirm that it's happening also with the reference example.

Thanks a lot for all your help debugging! Cheers :-)

**Comment by ptaoussanis** [comment] 2016-05-11 02:38
In case this is the point of confusion- it's normal for a disconnect to reflect in the `:connected-uids` atom only after 5 seconds. This is [by design](https://github.com/ptaoussanis/sente/blob/e55bed9e35f15819b64084975a0800586acab3e3/src/taoensso/sente.cljx#L540).

Is that maybe the behaviour you were identifying as broken?

**Comment by altV** [comment] 2016-05-11 05:12
Nope. It stays forever with both immutant and http-kit.

Scenario 1 - good one. tested with http-kit 2.1.19, http-kit 2.2.0-alpha, and immutant 2.1.4.
1. phone loads web page
2. it appears on server under connected-uids under :ws
3. I click back button on the phone
4. it dissapears after 5 seconds.

Scenario 2 - problematic one. tested with http-kit 2.1.19, http-kit 2.2.0-alpha, and immutant 2.1.4.
1. phone loads web page
2. it appears on server under connected-uids under :ws
3. I either turn the phone off or enable flight mode.
4. it stays forever in connected-uids until next refreshing the page (with flight mode disabled, of course).

I'm in hotel now so I can't experiment until tomorrow, but I guess I need to 1. test it with example project with much more logging, and then after probably 2. build minimal websocket server with http-kit and see how it interacts with websockets and which events get sent.

**Comment by altV** [comment] 2016-05-11 06:16
umm. well, now that I'm reading the Internet and the design of TCP protocol - is it a feature, not a bug?

Websockets are handled over TCP, and they say TCP does not handle all the disconnects, only proper explicit ones, so does it mean that in order to detect timeouts within some interval I should enable some application level keep-alives with this desired interval?

**Comment by ptaoussanis** [comment] 2016-05-11 06:46
You should still see the uid eventually get auto-removed from your connected uids set after Sente's next WebSocket keepalive attempt fails though.

Sente's default WebSocket keepalive is 25 seconds.

When you switch off your phone / switch on airplane mode - is the uid still around in 26 seconds?

**Comment by ptaoussanis** [comment] 2016-05-11 06:50
Hmm, scratch that; obviously won't work if you've switched your phone off (the keepalive is currently initiated by the client).

This may well be an edge case I hadn't considered that should be addressed Sente side. Let me think about this some + get back to you. Any other thoughts of course welcome in the meantime.

**Comment by ptaoussanis** [comment] 2016-05-11 07:18
What OS are you running your Sente server on? Any idea what your kernel TCP keepalive params are?

**Comment by ptaoussanis** [comment] 2016-05-11 11:00
@altV Have just pushed `[com.taoensso/sente "1.8.3-issue230"]` to Clojars. Could I possibly ask you to test this version when you get a chance?

Just added a simple GC mechanism to catch dead WebSocket connections. Default settings will perform GC after 60 seconds of inactivity. I.e. after you enable airplane mode, you should now see the uid correctly disconnect after 60 seconds.

**Comment by theasp** [comment] 2016-05-11 13:05
@altV I'm curious, how long had you waited?  In theory they should be disconnected after a long time, 2 hours and 12 minutes for a Linux server with the default config: http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html

> This means that the keepalive routines wait for two hours (7200 secs) before sending the first keepalive probe, and then resend it every 75 seconds. If no ACK response is received for nine consecutive times, the connection is marked as broken.

@ptaoussanis Have you considered reversing the ping?  Often a server would ping a client, and if the client doesn't respond in a specified time it disconnects them.  IRC comes to mind:  https://tools.ietf.org/html/rfc1459#section-4.6.2

I don't see a downside to your approach though.

**Comment by ptaoussanis** [comment] 2016-05-11 13:17
@theasp Hi Andrew

> Have you considered reversing the ping?

I did (was my first inclination), but it'd require more busywork on the server side. A client->server ping is simpler to implement, and won't affect server performance (the clients bear administrative costs like tracking when pings might/not be necessary due to other messages recently being sent, etc.).

I.e. the current implementation is simpler + more efficient than a server->client ping would be to achieve the ~same result.

Does that make sense?

**Comment by theasp** [comment] 2016-05-11 13:22
Yes, perfect sense.  Thank you.

**Comment by danielcompton** [comment] 2016-05-11 23:31
I've been thinking about this, and I think this explains why we were seeing Heroku warning us that some connections were timing out. They were successfully killed, but I hadn't really understood why it was happening (sporadically).

**Comment by altV** [comment] 2016-05-12 00:39
thank you! very nice.
- timeout of 60 seconds seems to work
- I now understand why my nginx reverse proxy with proxy_read_timeout set to many hours didn't affect websocket connections
- I'm thinking of sending a pull-request now for the ability to configure these two values - this 60 second keepalive, and 5 seconds of detecting disconnects
- I'm seeing Heroku disconnect warnings as @danielcompton mentions - these are probably about these idle connections
- I cannot say for sure I have done enough testing today. Most likely, it works, but to be able to test it thoroughly, I will try to make these values configurable
- Today I saw that one safari browser established two websocket connections, but that might be related to code reloading (?)

**Comment by ptaoussanis** [comment] 2016-05-12 04:37
@altV, @danielcompton Could someone possibly post an example Heroku warning here?

@altV Replies inline:

> I'm thinking of sending a pull-request now for the ability to configure these two values 

Please note that the values are already configurable with the `:ws-conn-gc-ms` opt.

> Today I saw that one safari browser established two websocket connections, but that might be related to code reloading (?)

Yeah, that sounds like code reloading

> Just to be 100% sure, am I correct that now clients send application-level heartbeats every 60 seconds?

Sente clients have always automatically sent PINGs as a form of keepalive. These default to a 25 second interval, but may be skipped if other data was sent w/in the same window.

The thing that's changed is that the server will now keep track of how long it's been since it has seen a message from each client. If no message has been received in `ws-conn-gc-ms` time, the Sente server will assume that the connection has died and will close it from the server's end.

**Comment by danielcompton** [comment] 2016-05-12 20:31
The Heroku warning is:

```
399 <158>1 2016-05-12T08:21:59.319328+00:00 heroku router - - at=error code=H15 desc="Idle connection" method=GET path="/chsk?client-id=1329c96a-296d-476d-94e3-80d472b58921" host=myhost.com request_id=a01f4080-b84b-4fa4-908d-01a3b85ae2d2 fwd="49.255.227.193" dyno=web.1 connect=1ms service=6505617ms status=503 bytes=2262
```

**Comment by ptaoussanis** [comment] 2016-05-13 03:41
@danielcompton Thanks!

**Comment by altV** [comment] 2016-05-13 15:08
Umm. Unfortunately, I cannot provide more testing until the end of next week (pessimistically). We can close the issue and reopen it if there will be issues. I'll reply back by then.

**Comment by ptaoussanis** [comment] 2016-05-14 02:52
No problem, please take your time :-)

**Comment by ptaoussanis** [comment] 2016-05-15 08:41
This should in principle be resolved so going to close for now. Please feel free to reopen if you still happen to run into any issues again later. Cheers :-)

**Closed by ptaoussanis** 2016-05-15 08:41 UTC
Labels: bug

**Comment by altV** [comment] 2016-05-20 14:04
looks like it works, but I will do even more testing. Many thanks for your fix!
